/**
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TalonOne);
  }
}(this, function(expect, TalonOne) {
  'use strict';

  var instance;

  before(function() {
    const defaultClient = TalonOne.ApiClient.instance
    defaultClient.basePath = "http://localhost:9000"

    const api_key_v1 = defaultClient.authentications["api_key_v1"]
    api_key_v1.apiKey = process.env.IAPI_KEY
    api_key_v1.apiKeyPrefix = "ApiKey-v1"

    instance = new TalonOne.IntegrationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IntegrationApi', function() {
    describe('createAudienceV2', function() {
      it('should call createAudienceV2 successfully', function(done) {
        //uncomment below and update the code to test createAudienceV2
        //instance.createAudienceV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createCouponReservation', function() {
      it('should call createCouponReservation successfully', function(done) {
        //uncomment below and update the code to test createCouponReservation
        //instance.createCouponReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createReferral', function() {
      it('should call createReferral successfully', function(done) {
        //uncomment below and update the code to test createReferral
        //instance.createReferral(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createReferralsForMultipleAdvocates', function() {
      it('should call createReferralsForMultipleAdvocates successfully', function(done) {
        //uncomment below and update the code to test createReferralsForMultipleAdvocates
        //instance.createReferralsForMultipleAdvocates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAudienceMembershipsV2', function() {
      it('should call deleteAudienceMembershipsV2 successfully', function(done) {
        //uncomment below and update the code to test deleteAudienceMembershipsV2
        //instance.deleteAudienceMembershipsV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAudienceV2', function() {
      it('should call deleteAudienceV2 successfully', function(done) {
        //uncomment below and update the code to test deleteAudienceV2
        //instance.deleteAudienceV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCouponReservation', function() {
      it('should call deleteCouponReservation successfully', function(done) {
        //uncomment below and update the code to test deleteCouponReservation
        //instance.deleteCouponReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomerData', function() {
      it('should call deleteCustomerData successfully', function(done) {
        //uncomment below and update the code to test deleteCustomerData
        //instance.deleteCustomerData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerInventory', function() {
      it('should call getCustomerInventory successfully', async function() {
        //uncomment below and update the code to test getCustomerInventory

        const inventory = await instance.getCustomerInventory('example_prof_id', {
          profile: true,
        })
        console.log(
          "API called successfully. Returned data:\n" + JSON.stringify(inventory, null, 2)
        )
        expect(inventory).to.not.be(null)
        expect(inventory).to.not.be(undefined)
        expect(inventory.profile).to.not.be(undefined)
        expect(inventory.profile.id).to.be(10)
        // expect(inventory.profile.attributes).to.eql({
        //   Name: "wauw"
        // })
        
      });
    });
    describe('getCustomerSession', function() {
      it('should call getCustomerSession successfully', async function() {
        //uncomment below and update the code to test getCustomerSession
        const sess = await instance.getCustomerSession('my_unique_session_integration_id_3')
        console.log(
          "API called successfully. Returned data:\n" + JSON.stringify(sess, null, 2)
        )
        expect(sess).to.not.be(null)
        expect(sess).to.not.be(undefined)
        expect(sess.customerSession.integrationId).to.be('my_unique_session_integration_id_3')
        expect(sess.customerSession.state).to.be('closed')
        expect(sess.effects).length(1)
      });
    });
    describe('getLoyaltyBalances', function() {
      it('should call getLoyaltyBalances successfully', function(done) {
        //uncomment below and update the code to test getLoyaltyBalances
        //instance.getLoyaltyBalances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoyaltyCardBalances', function() {
      it('should call getLoyaltyCardBalances successfully', function(done) {
        //uncomment below and update the code to test getLoyaltyCardBalances
        //instance.getLoyaltyCardBalances(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoyaltyCardTransactions', function() {
      it('should call getLoyaltyCardTransactions successfully', function(done) {
        //uncomment below and update the code to test getLoyaltyCardTransactions
        //instance.getLoyaltyCardTransactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoyaltyProgramProfileTransactions', function() {
      it('should call getLoyaltyProgramProfileTransactions successfully', async function() {
        try {
          const transactions = await instance.getLoyaltyProgramProfileTransactions(43, 'testing_hashmaps')
          console.log(
            "API called successfully. Returned data:\n" + JSON.stringify(transactions, null, 2)
          )
          expect(transactions.hasMore).to.be(false)
          expect(transactions.data).length(1)
          expect(transactions.data[0].type).to.be('addition')
          expect(transactions.data[0].amount).to.be(10)
        } catch (error) {
          console.error(error)
        }
      });
    });
    describe('getReservedCustomers', function() {
      it('should call getReservedCustomers successfully', function(done) {
        //uncomment below and update the code to test getReservedCustomers
        //instance.getReservedCustomers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('linkLoyaltyCardToProfile', function() {
      it('should call linkLoyaltyCardToProfile successfully', function(done) {
        //uncomment below and update the code to test linkLoyaltyCardToProfile
        //instance.linkLoyaltyCardToProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reopenCustomerSession', function() {
      it('should call reopenCustomerSession successfully', async function() {
        try {
          const reSess = await instance.reopenCustomerSession('example_prof_id_js_v500')
          console.log(
            "API called successfully. Returned data:\n" + JSON.stringify(reSess, null, 2)
          )
          expect().to.be();
        } catch(error) {
          console.error(error)
        }
      });
    });
    describe('returnCartItems', function() {
      it('should call returnCartItems successfully', function(done) {
        //uncomment below and update the code to test returnCartItems
        //instance.returnCartItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncCatalog', function() {
      it('should call syncCatalog successfully', function(done) {
        //uncomment below and update the code to test syncCatalog
        //instance.syncCatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trackEventV2', function() {
      it('should call trackEventV2 successfully', function(done) {
        //uncomment below and update the code to test trackEventV2
        //instance.trackEventV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAudienceCustomersAttributes', function() {
      it('should call updateAudienceCustomersAttributes successfully', function(done) {
        //uncomment below and update the code to test updateAudienceCustomersAttributes
        //instance.updateAudienceCustomersAttributes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAudienceV2', function() {
      it('should call updateAudienceV2 successfully', function(done) {
        //uncomment below and update the code to test updateAudienceV2
        //instance.updateAudienceV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerProfileAudiences', function() {
      it('should call updateCustomerProfileAudiences successfully', function(done) {
        //uncomment below and update the code to test updateCustomerProfileAudiences
        //instance.updateCustomerProfileAudiences(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerProfileV2', function() {
      it('should call updateCustomerProfileV2 successfully', function(done) {
        //uncomment below and update the code to test updateCustomerProfileV2
        //instance.updateCustomerProfileV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerProfilesV2', function() {
      it('should call updateCustomerProfilesV2 successfully', function(done) {
        //uncomment below and update the code to test updateCustomerProfilesV2
        //instance.updateCustomerProfilesV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerSessionV2', function() {
      it('should call updateCustomerSessionV2 successfully', async function() {
        const integrationApi = new TalonOne.IntegrationApi();

        // Initializing a customer session object
        const customerSession = TalonOne.NewCustomerSessionV2.constructFromObject({
          profileId: 'test',
          cartItems: [
            {
              name: 'Döner King',
              sku: 'kd-100',
              quantity: 1,
              price: 2.00,
              category: 'pizzas'
            },
            {
              name: 'Spezi 500ml',
              sku: 'sp-50',
              quantity: 1,
              price: 2,
              category: 'beverages'
            },
            {
              name: 'Queen Döner',
              sku: 'qd-100',
              quantity: 1,
              price: 2.50,
              category: 'pizzas'
            },
            {
              name: 'Club Mate 330ml',
              sku: 'cm-33',
              quantity: 1,
              price: 1.80,
              category: 'beverages'
            }
          ],
          couponCodes: [
            'Cool-Summer!'
          ],
          state: 'closed',
        });

        //Initializing an integration request wrapping the customer session
        const integrationRequest = new TalonOne.IntegrationRequest(customerSession);

        const data = await integrationApi.updateCustomerSessionV2("example_prof_id_js_v500", integrationRequest)

        console.log(JSON.stringify(data, null, 2));

        // Parsing the returned effects list, please consult https://developers.talon.one/Integration-API/handling-effects-v2 for the full list of effects and their corresponding properties
        data.effects.forEach(effect => {
          switch(effect.effectType) {
            case 'setDiscount':
              // Initiating right props instance according to the effect type
              const setDiscountProps = TalonOne.SetDiscountEffectProps.constructFromObject(effect.props)
              // Initiating the right props class is not a necessity, it is only a suggestion here that could help in case of unexpected returned values from the API

              // Access the specific effect's properties
              console.log(`Set a discount '${setDiscountProps.name}' of ${setDiscountProps.value}`)
              break
            case 'acceptCoupon':
              // Work with AcceptCouponEffectProps' properties
              // ...
            default:
              // throw new Error(`Unhandled effect type from Talon.One integration: ${effect.effectType}`)
          }
        })
      });
    });
  });

}));
